### avoir la liste des campagnes par utilisateur
GET http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwidXNlcm5hbWUiOiJTeWx2YW5hcyIsImlhdCI6MTc3MzE0NTQxMiwiZXhwIjoxNzczMTUyNjEyfQ.qThYy2oEx_iRzQ3hq53kFQsvq2T522LjCerzLVVIQ4o
content-type: application/json

###
GET http://localhost:3000/campaigns/1/characters/me

### créer une campagne
POST http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwidXNlcm5hbWUiOiJTeWx2YW5hcyIsImlhdCI6MTc3MzE0NTQxMiwiZXhwIjoxNzczMTUyNjEyfQ.qThYy2oEx_iRzQ3hq53kFQsvq2T522LjCerzLVVIQ4o
content-type: application/json

{
  "camp_name": "La caravane de sombrelune",
  "mode": "campagne en ligne",
  "synopsis": "mouai"
}

### tentative avec un mauvais code invitation
POST http://localhost:3000/campaigns/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwidXNlcm5hbWUiOiJTeWx2YW5hcyIsImlhdCI6MTc3MjIxMDUwMiwiZXhwIjoxNzcyMjE3NzAyfQ.lut3m6DN8CjdTNQYRPsVqkoJvNN9Ikk5vGS9c-O1ZaE
content-type: application/json

{
  "invite_code": "AAAAA"
}

### tentative avec un bon code invitation
POST http://localhost:3000/campaigns/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwidXNlcm5hbWUiOiJKYXgiLCJpYXQiOjE3NzMyNDYzMTcsImV4cCI6MTc3MzI1MzUxN30.oEda4UHnmRXUJMLAdvIHBkUwv8IJdhb5e4SoPIwHkxM
content-type: application/json

{
  "invite_code": "OVKHW9U0"
}

###
POST http://localhost:3000/campaigns/2/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwidXNlcm5hbWUiOiJKYXgiLCJpYXQiOjE3NzMyNDYzMTcsImV4cCI6MTc3MzI1MzUxN30.oEda4UHnmRXUJMLAdvIHBkUwv8IJdhb5e4SoPIwHkxM
content-type: application/json

{ 
  "char_name": "Talkor", 
  "race": "Humain", 
  "char_class": "Guerrier", 
  "exp": 120, 
  "hp": 550, 
  "mana": 1700, 
  "gold": 30, 
  "strength": 3, 
  "constitution": 4, 
  "dexterity": 2, 
  "intelligence": 10, 
  "wisdom": 6, 
  "charisma": 10 
  }

###
GET http://localhost:3000/campaigns/2/characters/me 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwidXNlcm5hbWUiOiJTeWx2YW5hcyIsImlhdCI6MTc3MzMyMzU0NCwiZXhwIjoxNzczMzMwNzQ0fQ.H08r-BDg8hf9c-FgsOD7j1Y2gyNcPAYE59BtLLQcanc
content-type: application/json

###
GET http://localhost:3000/campaigns/2/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwidXNlcm5hbWUiOiJKYXgiLCJpYXQiOjE3NzMyNDYzMTcsImV4cCI6MTc3MzI1MzUxN30.oEda4UHnmRXUJMLAdvIHBkUwv8IJdhb5e4SoPIwHkxM
content-type: application/json