
### créer une campagne
POST http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJuZW8iLCJpYXQiOjE3NzIxMTEzNDcsImV4cCI6MTc3MjExODU0N30.kmSKamfJWevARcBKfQm8VbpgLkkfXTlGh9TP0sZNFjI
content-type: application/json

{
  "camp_name": "La puissance",
  "mode": "campagne Physique",
  "synopsis": "azeaze"
}

### tentative avec un mauvais code invitation
POST http://localhost:3000/campaigns/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJ0aHJhbGwiLCJpYXQiOjE3NzIxMTM5NDksImV4cCI6MTc3MjEyMTE0OX0.eUbQ3E5ughSsmlgH7HskgXcKpUKpWfIjk7Fv7Z54XIw
content-type: application/json

{
  "invite_code": "AAAAA"
}

### tentative avec un bon code invitation
POST http://localhost:3000/campaigns/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJ0aHJhbGwiLCJpYXQiOjE3NzIxMTM5NDksImV4cCI6MTc3MjEyMTE0OX0.eUbQ3E5ughSsmlgH7HskgXcKpUKpWfIjk7Fv7Z54XIw
content-type: application/json

{
  "invite_code": "UBFMH6RM"
}

###
POST http://localhost:3000/campaigns/1/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJ0aHJhbGwiLCJpYXQiOjE3NzIxMTM5NDksImV4cCI6MTc3MjEyMTE0OX0.eUbQ3E5ughSsmlgH7HskgXcKpUKpWfIjk7Fv7Z54XIw
content-type: application/json

{ 
  "char_name": "pazeaorde", 
  "race": "Orc", 
  "char_class": "priest", 
  "exp": 120, 
  "hp": 450, 
  "mana": 1700, 
  "gold": 30, 
  "strength": 3, 
  "constitution": 4, 
  "dexterity": 2, 
  "intelligence": 10, 
  "wisdom": 6, 
  "charisma": 10 
  }