### ROUTE POUR RECUPERER LES OBJETS D'UN PERSONNAGE
GET http://localhost:3000/characters/1/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0IiwidXNlcm5hbWUiOiJNYXgiLCJpYXQiOjE3NzMxNDcyMzAsImV4cCI6MTc3MzE1NDQzMH0.IKzWoKNNLjX9fwVSO54kgMYGnLnQSbfGfwOAjP7EpBc

### ROUTE TEST POUR INSERER DES OBJETS DANS L'INVENTAIRE D'UN PERSONNAGE
POST http://localhost:3000/characters/1/items