GET http://localhost:3000/

###

GET http://localhost:3000/users/test

###

POST http://localhost:3000/users/register
content-type: application/json

{
  "email": "email@test.fr",
  "username": "Anduin",
  "password": "hashed"
}
