GET http://localhost:3000/

###

GET http://localhost:3000/users/test

###

POST http://localhost:3000/users/register
content-type: application/json

{
  "email": "yahou@yh.fr",
  "username": "Thrall",
  "password": "test"
}

###
POST http://localhost:3000/users/login
content-type: application/json

{
  "username": "Thrall",
  "password": "test"
}