GET http://localhost:3000/

###

POST http://localhost:3000/users/register
content-type: application/json

{
  "email": "ea@gmail.fr",
  "username": "Sylvanas",
  "password": "test"
}

###
POST http://localhost:3000/users/login
content-type: application/json

{
  "username": "Sylvanas",
  "password": "test"
}

###

GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwidXNlcm5hbWUiOiJTeWx2YW5hcyIsImlhdCI6MTc3MjIwOTQ3OCwiZXhwIjoxNzcyMjE2Njc4fQ.rajnCZpgU7irwAZlj1FKFNVq7ozAv6uwnXn-aci_FPA
