GET http://localhost:3000/

###

POST http://localhost:3000/users/register
content-type: application/json

{
  "email": "jax@gmail.fr",
  "username": "Jax",
  "password": "test"
}

###
POST http://localhost:3000/users/login
content-type: application/json

{
  "username": "Sylvanas",
  "password": "test"
}

###

GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwidXNlcm5hbWUiOiJTeWx2YW5hcyIsImlhdCI6MTc3MzMyMzU0NCwiZXhwIjoxNzczMzMwNzQ0fQ.H08r-BDg8hf9c-FgsOD7j1Y2gyNcPAYE59BtLLQcanc